import datetime

today = datetime.date.today()
parameters = {
    "t2m": 167,
    "tp": 228228,
}
fc_steps = range(0, 18 + 6, 6)

rule snakemake_ecflow_research_suite:
    input:
        "report.pdf"

rule build_env:
    output: "env_modules.txt"
    group: "make/envs"
    shell: "module list > {output}"

rule report:
    input:
        figures=expand("{parameter}/{step}.png", parameter=parameters.keys(), step=fc_steps),
        env=rules.build_env.output
    output: "report.pdf"
    shell: "convert {input.figures} -quality 100 {output}"


rule download_data:
    output: "data.grb"
    shell:
        f"""
        mars <<EOF
        retrieve,
            class=ai,
            date={today - datetime.timedelta(days=6):%Y-%m-%d}/to/{today:%Y-%m-%d},
            expver=1,
            levtype=sfc,
            model=aifs-single,
            param={'/'.join(map(str, parameters.values()))},
            step={'/'.join(map(str, fc_steps))},
            stream=oper,
            time=00:00:00,
            type=fc,
            target="{{output}}"
EOF
        """

rule figures:
    input: "data.grb"
    output: "{parameter}/{step}.png"
    envmodules: "python3"
    shell:
        """
        ipython -c "
        import xarray as xr, numpy as np, matplotlib.pyplot as plt
        step = np.timedelta64({wildcards.step}, 'h')
        ds = xr.open_dataset('{input}').{wildcards.parameter}.sel(step=step).mean(dim='time')
        fig = plt.figure(figsize=(10, 5))
        plt.scatter(ds.longitude, ds.latitude, c=ds.values, cmap='viridis', s=0.1)
        plt.colorbar(label='{wildcards.parameter}')
        plt.title('{wildcards.parameter} at step {wildcards.step}')
        fig.savefig('{output}', bbox_inches='tight')
        "
        """
